# Generated by Django 4.2.6 on 2024-08-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pincode_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Enterprise', 'Enterprise'), ('Government', 'Government')], default='Individual', max_length=20),
        ),
    ]
