# Generated by Django 4.2.6 on 2024-08-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_pincode_country_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='country',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
