# Generated by Django 4.2.6 on 2024-08-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pincode_country_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
